

all: min.exe
min.exe: min.cpp
	g++ -o$@ $<

all: min1.exe
min1.exe: min1.cpp
	g++ -o$@ $<
all: min2.exe
min2.exe: min2.cpp
	g++ -o$@ $<

all: min-stty-dsr6.exe
min-stty-dsr6.exe: min-stty-dsr6.cpp
	g++ -o$@ $<

all: min-redir-read.exe
min-redir-read.exe: min-redir-read.cpp
	g++ -o$@ $<

all: min-input-avail.exe
min-input-avail.exe: min-input-avail.cpp
	g++ -o$@ $<
